{{ config(materialized='view') }}

with source as (

    select * from {{ source('credit_risk', 'loan') }}

),

renamed as (

    select
        {{ dbt_utils.generate_surrogate_key(['id']) }} as loan_id,
        {{ dbt_utils.generate_surrogate_key(['member_id']) }} as member_id,
        cast(loan_amnt as int) as loan_amnt,
        cast(funded_amnt as int) as funded_amnt,
        cast(funded_amnt_inv as int) as funded_amnt_inv,
        cast(left(trim(term), 2) as int) as term_months,
        int_rate,
        installment as monthly_fee,
        trim(grade) as grade,
        trim(sub_grade) as sub_grade,
        coalesce(emp_title, 'Unemployed') as employ,
        trim(emp_length) as emp_length,
        trim(home_ownership) as home_ownership,
        floor(annual_inc) as annual_inc,
        trim(verification_status) as verification_status,
        to_char(to_date(issue_d, 'MON-YYYY'), 'MM-YYYY') as issue_d,
        trim(loan_status) as loan_status,
        cast(case when pymnt_plan='y' then TRUE else FALSE end as boolean) as pymnt_plan,
        url,
        desc,
        purpose,
        title,
        zip_code,
        addr_state,
        dti,
        delinq_2yrs,
        earliest_cr_line,
        inq_last_6mths,
        mths_since_last_delinq,
        mths_since_last_record,
        open_acc,
        pub_rec,
        revol_bal,
        revol_util,
        total_acc,
        initial_list_status,
        out_prncp,
        out_prncp_inv,
        total_pymnt,
        total_pymnt_inv,
        total_rec_prncp,
        total_rec_int,
        total_rec_late_fee,
        recoveries,
        collection_recovery_fee,
        last_pymnt_d,
        last_pymnt_amnt,
        next_pymnt_d,
        last_credit_pull_d,
        collections_12_mths_ex_med,
        mths_since_last_major_derog,
        policy_code,
        application_type,
        annual_inc_joint,
        dti_joint,
        verification_status_joint,
        acc_now_delinq,
        tot_coll_amt,
        tot_cur_bal,
        open_acc_6m,
        open_il_6m,
        open_il_12m,
        open_il_24m,
        mths_since_rcnt_il,
        total_bal_il,
        il_util,
        open_rv_12m,
        open_rv_24m,
        max_bal_bc,
        all_util,
        total_rev_hi_lim,
        inq_fi,
        total_cu_tl,
        inq_last_12m

    from source

)

select * from renamed